# Market Analysis Configuration
symbols:
  - BTCUSDT
  - ETHUSDT
  - SOLUSDT
  - XRPUSDT
  - ADAUSDT
  - DOGEUSDT
  - DOTUSDT
  - MATICUSDT
  - LTCUSDT
  - LINKUSDT
  - XLMUSDT
  - DYDXUSDT
  - UNIUSDT
  - AVAXUSDT
  - ZECUSDT
  - ZKUSDT
  - STRKUSDT
  - DASHUSDT
  - SUIUSDT
  - 1000PEPEUSDT
  - 1000SHIBUSDT

# Timeframe Settings
interval: "1h"
loopback: 1000
use_closed_candles: true

# Monitor Settings
monitor_frequency_minutes: 15
